services:
  apigateway.api:
    container_name: apigateway.api
    image: apigateway.api
    build:
      context: .
      dockerfile: ApiGateway.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080;http://+:8081"
      Redis__Host: "redis"
      Redis__Port: "6379"
      Redis__Db: "0"
    depends_on:
      - redis
      - catalogservice.api
      - catalogservice2.api
    networks:
      - backend

  catalogservice.api:
    container_name: catalogservice.api
    image: catalogservice.api
    build:
      context: .
      dockerfile: CatalogServicec.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      MongoDbSettings__ConnectionString: "mongodb://mongo:27017/GatewayDb"
      MongoDbSettings__DatabaseName: "GatewayDb"
    ports:
      - "5002:8080"   # optional: lets you hit Catalog from host at localhost:5002
    depends_on:
      - mongo
    networks:
      - backend
    
  catalogservice2.api:
    container_name: catalogservice2.api
    image: catalogservice.api
    build:
      context: .
      dockerfile: CatalogServicec.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      MongoDbSettings__ConnectionString: "mongodb://mongo:27017/GatewayDb"
      MongoDbSettings__DatabaseName: "GatewayDb"
    ports:
      - "5003:8080"  
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:8
    container_name: gateway_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
  
  redis:
    image: redis:7-alpine
    container_name: gateway_redis
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
